services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test_pass
      - POSTGRES_DB=grading_app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80

volumes:
  postgres:
  pgadmin-data:
